spring:
  application:
    name: EMPLOYEE-ZUUL-SERVICE
    
server:
  port: 9001
  
info:
  app:
    name: ZUUL Service - Instance
    description: My Boot App
    version: 1.0.0
    
zuul:
  routes:
    producer:
      path: /producer/**
      service-id: employee-producer
      
eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer1:8090/eureka,http://peer2:8091/eureka
      defaultZone: http://peer1:8090/eureka
    enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true
    status-page-url: http://${eureka.instance.hostname}:${server.port}/info
    health-check-url-path: http://${eureka.instance.hostname}:${server.port}/health
    
ribbon:
  eureka:
    enabled: true